# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 374bb42a29d5ce7b46d00c5a90f33f5de3e1110eafd376fc2122f7a064ab49ff162260b5c704a558b9553424b0147a77855ad2d70fedbdf9fd544723ef804274

test:
  secret_key_base: b2c86e11723f27fa68b9dfb03098e1206e9710b5814ec20401b19449ff3e4eed5e51de87dd8802227f98cb3fc3d26ef52e7fe6df389b1f316771aa6b1e44d4a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
